In [1]:
import numpy as np
import numpy.random as npr

In [2]:
array_1 = [[1,2],[3,4]]
array_2 = [[5,6],[7,8]] 

In [4]:
np.concatenate((array_1, array_2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
np.concatenate((array_1, array_2), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [9]:
x = npr.randint(20, size=20).reshape(10,2)

In [13]:
x

array([[ 4,  1],
       [ 4, 10],
       [10,  6],
       [ 7, 10],
       [ 4, 18],
       [10, 17],
       [14, 18],
       [ 7,  5],
       [17, 12],
       [ 2,  6]])

In [10]:
y = np.arange(10)

In [12]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
z = np.append(x,y)

In [16]:
z

array([ 4,  1,  4, 10, 10,  6,  7, 10,  4, 18, 10, 17, 14, 18,  7,  5, 17,
       12,  2,  6,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [18]:
np.concatenate((x,y))

ValueError: all the input arrays must have same number of dimensions

In [19]:
k = z.reshape(10,3)

In [20]:
k

array([[ 4,  1,  4],
       [10, 10,  6],
       [ 7, 10,  4],
       [18, 10, 17],
       [14, 18,  7],
       [ 5, 17, 12],
       [ 2,  6,  0],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])